#!/usr/bin/env bash

#Script for executing leelaz remotely.

set -eu
# source ../config.sh
gcloud compute ssh --project alexpenson-cs231 --zone europe-west4-a instance-1 --command '/home/pensona/leela-zero/build/leelaz --gtp --threads 3 --noponder --weights /home/pensona/best-network.gz'
